/*  This file is part of the Rade project (https://github.com/mgimpel/rade).
 *  Copyright (C) 2018 Marc Gimpel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* $Id$ */
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('2204','01001','L ABERGEMENT CLEMENCIAT',0,'M',null,'01400','L ABERGEMENT CLEMENCIAT',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('2205','01002','L ABERGEMENT DE VAREY',0,'M',null,'01640','L ABERGEMENT DE VAREY',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('2206','01004','AMBERIEU EN BUGEY',0,'M',null,'01500','AMBERIEU EN BUGEY',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561682','01004','AMBERIEU EN BUGEY',0,'C',null,'01501','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561683','01004','AMBERIEU EN BUGEY',0,'C',null,'01502','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561684','01004','AMBERIEU EN BUGEY',0,'C',null,'01503','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561685','01004','AMBERIEU EN BUGEY',0,'C',null,'01504','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561686','01004','AMBERIEU EN BUGEY',0,'C',null,'01505','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561687','01004','AMBERIEU EN BUGEY',0,'C',null,'01506','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
Insert into ZR_HEXAPOSTE (IDENTIFIANT,CODE_INSEE_COMMUNE,LIBELLE_COMMUNE,INDICATEUR_PLURIDISTRIBUTION,TYPE_CODE_POSTALE,LIBELLE_LIGNE5,CODE_POSTALE,LIBELLE_ACHEMINEMENT,CODE_INSEE_ANCIENNE_COMMUNE,CODE_MAJ,CODE_ETENDU_ADRESSE,AUDIT_ID) values ('561688','01004','AMBERIEU EN BUGEY',0,'C',null,'01508','AMBERIEU EN BUGEY CEDEX',null,null,null,1);
