/*  This file is part of the Rade project (https://github.com/mgimpel/rade).
 *  Copyright (C) 2018 Marc Gimpel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* $Id$ */
-- Généalogie Départements
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (200, 201, '100', 'Reconstruction manuelle');
--INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (0, 202, '200', 'Création Mayotte');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (148, 203, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (150, 204, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (183, 205, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (185, 206, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (191, 207, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (142, 208, '100', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (101, 209, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (102, 210, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (103, 211, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (107, 212, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (108, 213, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (109, 214, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (110, 215, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (111, 216, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (112, 217, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (114, 218, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (115, 219, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (116, 220, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (117, 221, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (119, 222, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (122, 223, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (124, 224, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (125, 225, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (126, 226, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (127, 227, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (128, 228, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (131, 229, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (132, 230, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (133, 231, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (134, 232, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (135, 233, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (139, 234, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (140, 235, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (141, 236, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (143, 237, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (144, 238, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (147, 239, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (203, 240, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (149, 241, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (151, 242, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (152, 243, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (153, 244, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (155, 245, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (156, 246, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (158, 247, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (159, 248, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (160, 249, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (161, 250, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (162, 251, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (163, 252, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (164, 253, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (165, 254, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (166, 255, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (167, 256, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (168, 257, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (169, 258, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (170, 259, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (171, 260, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (172, 261, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (174, 262, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (175, 263, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (177, 264, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (180, 265, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (181, 266, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (182, 267, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (205, 268, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (187, 269, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (188, 270, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (189, 271, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (190, 272, '400', 'Reconstruction manuelle');
INSERT INTO ZR_GENEALOGIE ("PARENT", "ENFANT", "TYPE_GENEALOGIE", "COMMENTAIRE") VALUES (207, 273, '400', 'Reconstruction manuelle');
