/*  This file is part of the Rade project (https://github.com/mgimpel/rade).
 *  Copyright (C) 2018 Marc Gimpel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* $Id$ */
-- Données 1999 à 2018 extrait des fichiers INSEE reg1999.txt à reg2018.txt
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (1,'1999-01-01',null,null,'GUADELOUPE','Guadeloupe','','3','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (2,'1999-01-01',null,null,'MARTINIQUE','Martinique','','3','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (3,'1999-01-01',null,null,'GUYANE','Guyane','','3','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (4,'1999-01-01','2004-01-01',null,'REUNION','Réunion','','3','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (5,'1999-01-01',null,null,'ILE-DE-FRANCE','Île-de-France','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (6,'1999-01-01','2016-01-01',null,'CHAMPAGNE-ARDENNE','Champagne-Ardenne','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (7,'1999-01-01','2016-01-01',null,'PICARDIE','Picardie','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (8,'1999-01-01','2016-01-01',null,'HAUTE-NORMANDIE','Haute-Normandie','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (9,'1999-01-01','2016-01-01',null,'CENTRE','Centre','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (10,'1999-01-01','2016-01-01',null,'BASSE-NORMANDIE','Basse-Normandie','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (11,'1999-01-01','2016-01-01',null,'BOURGOGNE','Bourgogne','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (12,'1999-01-01','2016-01-01',null,'NORD-PAS-DE-CALAIS','Nord-Pas-de-Calais','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (13,'1999-01-01','2003-01-01',null,'LORRAINE','Lorraine','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (14,'1999-01-01','2016-01-01',null,'ALSACE','Alsace','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (15,'1999-01-01','2016-01-01',null,'FRANCHE-COMTE','Franche-Comté','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (16,'1999-01-01',null,null,'PAYS DE LA LOIRE','Pays de la Loire','','4','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (17,'1999-01-01',null,null,'BRETAGNE','Bretagne','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (18,'1999-01-01','2016-01-01',null,'POITOU-CHARENTES','Poitou-Charentes','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (19,'1999-01-01','2016-01-01',null,'AQUITAINE','Aquitaine','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (20,'1999-01-01','2016-01-01',null,'MIDI-PYRENEES','Midi-Pyrénées','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (21,'1999-01-01','2016-01-01',null,'LIMOUSIN','Limousin','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (22,'1999-01-01','2014-01-01',null,'RHONE-ALPES','Rhône-Alpes','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (23,'1999-01-01','2016-01-01',null,'AUVERGNE','Auvergne','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (24,'1999-01-01','2016-01-01',null,'LANGUEDOC-ROUSSILLON','Languedoc-Roussillon','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (25,'1999-01-01',null,null,'PROVENCE-ALPES-COTE D''AZUR','Provence-Alpes-Côte d''Azur','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (26,'1999-01-01',null,null,'CORSE','Corse','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (27,'2003-01-01','2016-01-01',null,'LORRAINE','Lorraine','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (28,'2004-01-01',null,null,'LA REUNION','La Réunion','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (29,'2012-01-01',null,null,'MAYOTTE','Mayotte','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (30,'2014-01-01','2016-01-01',null,'RHONE-ALPES','Rhône-Alpes','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (31,'2016-01-01',null,null,'CENTRE-VAL DE LOIRE','Centre-Val de Loire','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (32,'2016-01-01',null,null,'BOURGOGNE-FRANCHE-COMTE','Bourgogne-Franche-Comté','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (33,'2016-01-01',null,null,'NORMANDIE','Normandie','','0','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (34,'2016-01-01','2017-01-01',null,'NORD-PAS-DE-CALAIS-PICARDIE','Nord-Pas-de-Calais-Picardie','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (35,'2016-01-01','2017-01-01',null,'ALSACE-CHAMPAGNE-ARDENNE-LORRAINE','Alsace-Champagne-Ardenne-Lorraine','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (36,'2016-01-01','2017-01-01',null,'AQUITAINE-LIMOUSIN-POITOU-CHARENTES','Aquitaine-Limousin-Poitou-Charentes','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (37,'2016-01-01','2017-01-01',null,'LANGUEDOC-ROUSSILLON-MIDI-PYRENEES','Languedoc-Roussillon-Midi-Pyrénées','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (38,'2016-01-01',null,null,'AUVERGNE-RHONE-ALPES','Auvergne-Rhône-Alpes','','1','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (39,'2017-01-01',null,null,'HAUTS-DE-FRANCE','Hauts-de-France','','4','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (40,'2017-01-01',null,null,'GRAND EST','Grand Est','','2','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (41,'2017-01-01',null,null,'NOUVELLE-AQUITAINE','Nouvelle-Aquitaine','','3','REG',1);
Insert into ZR_ENTITEADMIN (ID,DEBUT_VALIDITE,FIN_VALIDITE,ARTICLE_ENRICHI,NOM_MAJUSCULE,NOM_ENRICHI,COMMENTAIRE,TYPE_NOM_CLAIR,TYPE_ENTITE_ADMIN,AUDIT_ID) values (42,'2017-01-01',null,null,'OCCITANIE','Occitanie','','1','REG',1);
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (1,'01','97105');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (2,'02','97209');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (3,'03','97302');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (4,'04','97411');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (5,'11','75056');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (6,'21','51108');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (7,'22','80021');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (8,'23','76540');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (9,'24','45234');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (10,'25','14118');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (11,'26','21231');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (12,'31','59350');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (13,'41','54395');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (14,'42','67482');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (15,'43','25056');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (16,'52','44109');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (17,'53','35238');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (18,'54','86194');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (19,'72','33063');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (20,'73','31555');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (21,'74','87085');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (22,'82','69123');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (23,'83','63113');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (24,'91','34172');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (25,'93','13055');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (26,'94','2A004');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (27,'41','57463');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (28,'04','97411');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (29,'06','97608');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (30,'82','69123');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (31,'24','45234');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (32,'27','21231');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (33,'28','76540');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (34,'32','59350');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (35,'44','67482');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (36,'75','33063');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (37,'76','31555');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (38,'84','69123');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (39,'32','59350');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (40,'44','67482');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (41,'75','33063');
Insert into ZR_REGION (ID,CODE,CHEF_LIEU) values (42,'76','31555');
ALTER TABLE ZR_ENTITEADMIN ALTER ID RESTART WITH 50;
