/*  This file is part of the Rade project (https://github.com/mgimpel/rade).
 *  Copyright (C) 2018 Marc Gimpel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* $Id$ */
-- Données 2018 extrait du fichier INSEE reg2018.txt
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (1, '2018-01-01', NULL, NULL, 'GUADELOUPE', 'Guadeloupe', '', 'REG', '3', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (2, '2018-01-01', NULL, NULL, 'MARTINIQUE', 'Martinique', '', 'REG', '3', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (3, '2018-01-01', NULL, NULL, 'GUYANE', 'Guyane', '', 'REG', '3', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (4, '2018-01-01', NULL, NULL, 'LA REUNION', 'La Réunion', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (5, '2018-01-01', NULL, NULL, 'MAYOTTE', 'Mayotte', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (6, '2018-01-01', NULL, NULL, 'ILE-DE-FRANCE', 'Île-de-France', '', 'REG', '1', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (7, '2018-01-01', NULL, NULL, 'CENTRE-VAL DE LOIRE', 'Centre-Val de Loire', '', 'REG', '2', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (8, '2018-01-01', NULL, NULL, 'BOURGOGNE-FRANCHE-COMTE', 'Bourgogne-Franche-Comté', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (9, '2018-01-01', NULL, NULL, 'NORMANDIE', 'Normandie', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (10, '2018-01-01', NULL, NULL, 'HAUTS-DE-FRANCE', 'Hauts-de-France', '', 'REG', '4', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (11, '2018-01-01', NULL, NULL, 'GRAND EST', 'Grand Est', '', 'REG', '2', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (12, '2018-01-01', NULL, NULL, 'PAYS DE LA LOIRE', 'Pays de la Loire', '', 'REG', '4', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (13, '2018-01-01', NULL, NULL, 'BRETAGNE', 'Bretagne', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (14, '2018-01-01', NULL, NULL, 'NOUVELLE-AQUITAINE', 'Nouvelle-Aquitaine', '', 'REG', '3', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (15, '2018-01-01', NULL, NULL, 'OCCITANIE', 'Occitanie', '', 'REG', '1', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (16, '2018-01-01', NULL, NULL, 'AUVERGNE-RHONE-ALPES', 'Auvergne-Rhône-Alpes', '', 'REG', '1', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (17, '2018-01-01', NULL, NULL, 'PROVENCE-ALPES-COTE D''AZUR', 'Provence-Alpes-Côte d''Azur', '', 'REG', '0', 1);
INSERT INTO ZR_ENTITEADMIN ("ID", "DEBUT_VALIDITE", "FIN_VALIDITE", "ARTICLE_ENRICHI", "NOM_MAJUSCULE", "NOM_ENRICHI", "COMMENTAIRE", "TYPE_ENTITE_ADMIN", "TYPE_NOM_CLAIR", "AUDIT_ID") VALUES (18, '2018-01-01', NULL, NULL, 'CORSE', 'Corse', '', 'REG', '0', 1);
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (1, '01', '97105');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (2, '02', '97209');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (3, '03', '97302');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (4, '04', '97411');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (5, '06', '97608');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (6, '11', '75056');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (7, '24', '45234');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (8, '27', '21231');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (9, '28', '76540');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (10, '32', '59350');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (11, '44', '67482');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (12, '52', '44109');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (13, '53', '35238');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (14, '75', '33063');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (15, '76', '31555');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (16, '84', '69123');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (17, '93', '13055');
INSERT INTO ZR_REGION ("ID", "CODE", "CHEF_LIEU") VALUES (18, '94', '2A004');
ALTER TABLE ZR_ENTITEADMIN ALTER ID RESTART WITH 20;
