/*  This file is part of the Rade project (https://github.com/mgimpel/rade).
 *  Copyright (C) 2018 Marc Gimpel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* $Id$ */
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DBN', 'DIRECTION BOCAGES NORMANDS', 'HEROUVILLE ST CLAIR CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION BOCAGES NORMANDS', '1 RUE DE LA POMPE', 'CS 70087', '', '14203', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('PPC', 'DIRECTION DE PARIS PETITE COURONNE', 'NANTERRE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION PARIS PETITE COURONNE', '51 RUE SALVADOR ALLENDE', '', '', '92027', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DRIF', 'DIRECTION REGION ILE DE FRANCE', 'NANTERRE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION PARIS PETITE COURONNE', '51 RUE SALVADOR ALLENDE', '', '', '92027', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DSAM', 'DIRECTION SEINE AMONT', 'SENS CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION SEINE AMONT', '0018 CRS TARBE', 'CS 70702', '', '89107', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DSAV', 'DIRECTION SEINE AVAL', 'ROUEN CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION SEINE AVAL', 'HANGAR C', 'ESPACE DES MAREGRAPHES - CS 41174', '', '76176', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DVM', 'DIRECTION DES VALLEES DE MARNE', 'CHALONS EN CHAMPAGNE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION DES VALLEES DE MARNE', '30 CHAUSSEE DU PORT', 'CS 50423', '', '51035', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DVO', 'DIRECTION DES VALLEES DE L''OISE', 'COMPIEGNE', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION DES VALLEES DE L''OISE', '2 RUE DU DOCTEUR CAMILLE GUERIN', 'ZAC DE L''UNIVERSITE', '', '60200', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('VSGMO', 'DSI', 'NANTERRE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DSI', '51 RUE SALVADOR ALLENDE', '', '', '92027', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('WSGQU', 'DFI', 'NANTERRE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DFI', '51 RUE SALVADOR ALLENDE', '', '', '92027', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
INSERT INTO ZR_DELEGATION("CODE", "LIBELLE", "ACHEMINEMENT", "ADRESSE1", "ADRESSE2", "ADRESSE3", "ADRESSE4", "ADRESSE5", "CODE_POSTAL", "EMAIL", "FAX", "SITEWEB", "TELEPHONE", "TELEPHONE2", "TELEPHONE3")
VALUES ('DF', 'DIRECTION SEINE FRANCILIENNE', 'NANTERRE CEDEX', 'AGENCE DE L''EAU SEINE NORMANDIE', 'DIRECTION SEINE FRANCILIENNE', '51 RUE SALVADOR ALLENDE', '', '', '92027', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx');
